### ISSUE TITLE
Output the unlabled markers data to .csv file

### ISSUE THREAD

**Issue by Liming-Zheng** [ha5dzs/optitrack-motive-file-converter#4]
Hi! This is a very good project to convert .tak to .csv. I do have a lot of data, around 200GB. Some markers in my projects are unlabled. This project can only output rigid body. Could you please share some information about how to output the unmarker data.

**Comment by ha5dzs** [comment]
Well, the problem with these stray markers are that they all look the same.

The system will assign a UUID for each marker, but if the same marker vanishes even for just one frame, it will assign it a different UUID. Also, if you have anything shiny or flashing even for just one frame, it will also assign a marker UUID for it.

This is why I disabled the exporting of this data. In the lab, we only use rigid bodies for this reason. When the markers are assembled to a particular constellation, it is easier to recover the positions.

If you want to change this behaviour, just alter line 134 of `converter.cs` from false to true and recompile the project.

If you have continuous marker data in your recordings, everything will be fine. If you don't, then you will have more markers in your CSV file than what you have in the recording.

When developing this, I had 1000+ reported markers from a 6-marker set-up. So you have been warned, it can get really messy really quickly.

**Comment by Npickard98** [comment]
Hi,
I am trying to use this to access marker tracking from a .tak file as I do not have access to motive at present (it's a short capture in which the object/markers are static so shouldn't have a major issue with hundreds of markers). However, I am having an issue trying to recompile the .cs file into a .exe file after I have modified line 134. I do not have much experience with C# (I work mainly in Matlab). Can you please help with this at all?
Thanks and Happy Holidays

**Comment by ha5dzs** [comment]
Hi,

I am not a C# developer either. I am only using it because I have to. Otherwise, I would have gone nice low-level C and write a mex file.

* Set-up
I tried this on a new computer with vanilla windows, recent version of VSCode, and installed everything VSCode was complaining about as soon as I opened the cloned code. Don't download .NET 8 SDK, look for .NET 7 SDK. (I had to migrate from .NET 5, because Microsoft just killed it off and it's no longer available.) They are not reverse compatible, apparently. After some restarts, I also needed to log in to my Microsoft account to use the .NET framework.

* Compiling
In the top right corner of VSCode the third button from the right is the one that compiles the code. When clicking on the chevron next to it, you can change from 'Debug project associated with this file' to 'Run project associated with this file'. 
I did this step successfully with the downloaded code, then I changed Line 134 and compiled again, successfully.

* Where is the stuff
The compiled file will be in `bin\Debug\net7.0\*` in the same directory the cloned code is. It is not being synced to the repository, mainly to save space. For convenience, I rename `OptiTrack NMotive converter.exe` to `converter.exe`.

Simple, huh? :)

Now since I did this entire process to verify that it actually works, I [have these files available for download here](https://drive.google.com/file/d/10rRyUJpG7EtS4p2HNWGs8opOe_bL0kbv/view?usp=sharing). I haven't tested this feature of the converter with this new freshly-released NMotive library, so could you test it for me?

I am waiting for some info about the solving and processing settings, and then, I will eventually migrate all these things to a human-editable config file.

There are probably better and easier ways, but it is beyond my control.

(edit: typos)

**Comment by Liming-Zheng** [comment]
I already changed the false to true in 134 line, and built it. It was still only some of the markers. I think the exe only leave the markers which are live all the time, and delete the flashing markers even just one frame.

Here I upload two files, one is from your code, and another is from Motive software.
[test_using_code.csv](https://github.com/ha5dzs/optitrack-motive-file-converter/files/13949532/test_using_code.csv)
[test_using_motive_software.csv](https://github.com/ha5dzs/optitrack-motive-file-converter/files/13949542/test_using_motive_software.csv)

Do you have some ideas to improve the code to get the same results as from the Motive software?

**Comment by Npickard98** [comment]
Hmmm,
I'm unsure. The output from the two methods looks fairly different as well?
Is the global coordinate frame altered?
Nico

**Comment by Liming-Zheng** [comment]
Yes, coordinate frame is different and the unit as well. I upload the raw data as well
[test.zip](https://github.com/ha5dzs/optitrack-motive-file-converter/files/13950606/test.zip)

**Comment by ha5dzs** [comment]
I am having a similar problem as well with my rigid bodies. I think it has to do with the reconstruction settings. See:
[https://forums.naturalpoint.com/viewtopic.php?t=26411](https://forums.naturalpoint.com/viewtopic.php?t=26411)

With my data, when everything works fine, Motive and this code produces identical results. When the data is iffy, this code seems a bit more eager to drop the data.

It's a matter of changing the trajectoriser settings, but I haven't been able to try these settings yet.

You can either load the settings from an xml file, or set it inside the C# code.

I'll have a fiddle with this once I am finished with my adventures in various medical facilities.

**Comment by ha5dzs** [comment]
@Liming-Zheng, do you have something like 18 markers in your test recording?

**Comment by ha5dzs** [comment]
Okay, I think I can close this issue. I made a couple of new releases. Now you can configure every parameter that this code uses without having to compile any code. I could get all the marker data out as well as other information.

Just be mindful with the xml syntax and the deliberate typos in the parameters. Thank you both for helping with this :)
